### ISSUE TITLE
Concerns about the Dataset

### ISSUE THREAD

**Issue by yongsongH** [felihong/wavelet-PET-denoising#1]
Thank you so much for sharing, I've learned a lot from it! 

I still have some confusion about this and would appreciate it if you could kindly take some time to respond.
Concerning the dataset processing, I contacted the organizer to get the original dataset and the details are shown below:

<img width="207" alt="image" src="https://github.com/felihong/wavelet-PET-denoising/assets/23012102/b4023975-2abb-48eb-b85c-99339e1b267e"><img width="311" alt="image" src="https://github.com/felihong/wavelet-PET-denoising/assets/23012102/5d9f51ea-5fc7-4def-a214-a6bedf0483ec">

I'm a little confused that there seems to be a difference between this and the example given.
<img width="552" alt="image" src="https://github.com/felihong/wavelet-PET-denoising/assets/23012102/a7bb3a6f-31bf-4e9a-a638-a39589907537">

For me, as a newbie, it would mean a lot if you could give me some advice on how to deal with the dataset.
Thanks for your time and support!

**Comment by yongsongH** [comment]
@felihong Looking forward to your reply! Thanks in advance!

**Comment by felihong** [comment]
Hi @yongsongH , 

many thanks for your interest! 

As far as I recalled (it has been a while 😅), the provided dataset is in a `dicom` format, containing different doses levels of each subject. The `DataLoader` instance requires data in `nifti` format, all subjects' data in the same dose level is appended together. 

Feel free to take a look of the [dicom2Nifti](https://github.com/felihong/wavelet-PET-denoising/blob/cbbcb13b515bf93272c7d7a697a2d285692f5eef/common/utils.py#LL13C5-L13C16) function, I think this should give you some ideas to start with the data format conversion. 

Let me know if you have any further questions :)

**Comment by yongsongH** [comment]
Hi, @felihong 

Thank you very much for your reply!

I confirmed `dicom2Nifti`, which seems to be the function that converts image data in **DICOM** format to **NIFTI** format data.
And, I applied for access to the dataset from the organizer:

    
```
|-- Bern Siemens Vision Quadra
|   |-- Subject_1-6
|   |   |-- 01122021_1_20211201_164050
|   |   `-- ...
|   |-- Subject_7-12
|   |   |-- 01122021_1_20211201_164050
|   |   `-- ...
...
```

```
|-- UI_Explorer
|   |-- uExplorerPART1
|   |   |-- Anonymous_ANO_20220224_1824561_122859
|   |.  |   |-- 2.886 x 600 WB D2
|   |   `-- ...
|   |-- uExplorerPART2
|   |   `-- ...
...
```

Considering the situation, it seems I need to convert the data in **Bern Siemens Vision Quadra and UI_Explorer** to `nii `format first, with the help from dicom2Nifti.

I am just starting to experiment with PET image processing and wanted to follow your excellent work as a first step.
Sorry for the inconvenience.
If you could kindly provide me with some tips on data pre-processing, I would appreciate very much!
Sincerely hope you have a nice day! :)
